### PR TITLE
Update building script for qsim

### PR DESCRIPTION
**Pull request by sixshotx**
1, Initial script uses the aarch64 toolchain from the ubuntu distribution. When I test qsim using other distribution (i.e. fedora 21, arch), these distribution does not come with such toolchain by default. The new script downloads the aarch64 toolchain direct from the linaro website to avoid the distro-dependent problem.

2, extend the mkstate.sh to generate new arm64 state files.

### CODE REVIEW

**Comment by pranith** [comment]
@sixshotx Thanks for the patch.

Can you check your branch? There are two commits in this PR, the first of which is a merge. That should not be there. (try rebasing your patch on top of gtcasl/qsim/master). You can fix it and push (use --force) to update the PR directly.

**Comment by sixshotx** [comment]
OK. So I will submit another PR?

**Comment by sixshotx** [comment]
I think it is better to put everything required by the qsim into the qsim directory.

**Comment by pranith** [comment]
You can just push your changes after fixing them to the same branch(your master branch). They will show up in this PR.

**Comment by sixshotx** [comment]
Yet there is already another key stop right before installing dependencies?

**Comment by pranith** [comment]
Yes, that is the prompt waiting for users to copy/paste the environment variables to their bashrc. Once they are done copying, they will continue installing.

**Comment by sixshotx** [comment]
I am moving the lines to below, as I want to put the echo information closer to the actual download action.

**Comment by sixshotx** [comment]
I came to remember that you had hard coded the path of the disk images. I would need to modify the qsim.cpp in order to update the image location.

**Comment by pranith** [comment]
yes, we need to modify the hard-coded location in all the interactive mode examples I guess.

**Pull request closed without merging**
