### PR TITLE
Use qemu deterministic execution

### PR DESCRIPTION
**Pull request by pranith**
Hugh observed that running on a slow processor changed the behavior of execution within the VM. This is mainly caused because when we are simulating in the callbacks, the timer in the VM keeps ticking causing timer interrupt to fire off even though the execution time slice is not done.

This is fixed in this PR by using qemu's deterministic execution. I tested this on a really old(2007, Intel Core 2 Quad, 2.6 GHz) machine which I got hold of in my lab and setup qsim environment. I compared this execution with an execution on a recent processor(2012, Core i7-3770K, 4.5 GHz) and the execution is comparable.

Thanks to Hugh for finding this bug and being persistent to get it fixed!

### CODE REVIEW

**Comment by sixshotx** [comment]
Did you test different granularity (i.e. 500~10000)?

Regards, H

**Comment by pranith** [comment]
yes, tested 100 and 1000 granularity.

**Comment by sixshotx** [comment]
Nice. Let me pull out the commit and test it against manifold.

Regards, H

**Comment by sixshotx** [comment]
The fix solved the problems of missing callbacks and granularity dependency when executing run() in qsim.

**Comment by pranith** [comment]
@sixshotx thanks for confirming!

**Pull request merged**
